
USE [Inventory]
GO

-- =============================================
-- Author:		HarshalC
-- Create date: 16-OCT-2021
-- Description:	insert and update records 
-- exec [INSERT_UPDATE_PRODUCT_DETAILS]
-- =============================================
alter PROCEDURE [dbo].[INSERT_UPDATE_PRODUCT_DETAILS]
    @PRODUCT_ID INT = 0,
	@PRODUCT_NAME VARCHAR(255),
	@DISCRIPTTION VARCHAR(255),
    @RETAIL_PRICE INT, 
	@ACTUAL_PRICE INT,
    @CATEGORY 	  VARCHAR(255),
	@STATUS VARCHAR(1000) OUTPUT
AS

BEGIN
DECLARE @CREATE_DATE DATETIME
IF (@PRODUCT_ID = 0)
begin
	INSERT INTO PRODUCT_DETAILS 
			    (PRODUCT_NAME,
				DISCRIPTTION,
				RETAIL_PRICE, 
				ACTUAL_PRICE,
				CATEGORY,
				CREATE_DATE,
				IS_ACTIVE)
				VALUES 
				(@PRODUCT_NAME,
				@DISCRIPTTION,
				@RETAIL_PRICE,
				@ACTUAL_PRICE,
				@CATEGORY,
				GETDATE(),
				1)
    SET @STATUS='1' -- Success
	SET @PRODUCT_ID = SCOPE_IDENTITY()
end

ELSE
begin
	UPDATE PRODUCT_DETAILS
	SET PRODUCT_NAME = @PRODUCT_NAME,
	DISCRIPTTION = @DISCRIPTTION,
	RETAIL_PRICE = @RETAIL_PRICE,
	ACTUAL_PRICE = @ACTUAL_PRICE,
	CATEGORY = @CATEGORY
	WHERE PRODUCT_ID = @PRODUCT_ID AND IS_ACTIVE = 1

	SET @STATUS='1' -- Success
end
	


END
