
CREATE TABLE VENDOR_DETAILS (
	VENDOR_ID INT  PRIMARY KEY IDENTITY(1,1) NOT NULL,
    VENDOR_NAME VARCHAR(255), 
    Country VARCHAR(255),
	CITY VARCHAR(255),
	IS_ACTIVE BIT,
);

CREATE TABLE PRODUCT_DETAILS (
    PRODUCT_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    PRODUCT_NAME VARCHAR(255) ,
	DISCRIPTTION VARCHAR(255) ,
    RETAIL_PRICE INT,
	ACTUAL_PRICE INT, 
    CATEGORY VARCHAR(255), 
    CREATE_DATE DATETIME,
	UPDATE_DATE DATETIME,
	IS_ACTIVE BIT,
    
);
 
CREATE TABLE PURCHASE_DETAILS(
    PURCHASE_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL, 
	PURCHASED_QUANTITY INT,
	RETAIL_PRICE INT,
	ACTUAL_PRICE INT,
	TOTAL_PRICE INT,
    BUYER VARCHAR(255) NOT NULL,
	VENDOR_NAME VARCHAR(255),
	CREATE_DATE DATETIME,
	UPDATE_DATE DATETIME,
	IS_ACTIVE BIT,
    FOREIGN KEY (VENDOR_NAME) REFERENCES VENDOR_DETAILS(VENDOR_NAME),

);
 
CREATE TABLE SALES_DETAILS(
    SALES_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PRODUCT_ID INT,
    SALE_OUT_PRODUCT VARCHAR(255) NOT NULL, 
    BUYER VARCHAR(255) NOT NULL,
	IS_ACTIVE BIT,
	CREATE_DATE DATETIME,
	UPDATE_DATE DATETIME,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_DETAILS(PRODUCT_ID)
);

CREATE TABLE CUSTOMER_DETAILS(
    CUSTOMER_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	CUSTOMER_NAME VARCHAR(255) NOT NULL,
    PRODUCT_ID INT, 
	QUANTITY INT,
	PRICE INT,
	DISCOUNT_PRICE INT,
	TOTAL_PRICE INT,
    IS_ACTIVE BIT,
	CREATE_DATE DATETIME,
	UPDATE_DATE DATETIME,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_DETAILS(PRODUCT_ID)
);

CREATE TABLE ADMIN_USER (
    USERID INT IDENTITY(1,1) NOT NULL,
    USER_NAME VARCHAR(255), 
    PASSWORD VARCHAR(255),
	CHANGE_PASSWORD VARCHAR(255),
	CHANGE_USERNAME VARCHAR(255),
	IS_ACTIVE BIT,
	CREATE_DATE DATETIME,
	UPDATE_DATE DATETIME
);